### ISSUE TITLE
Connection list without any project

### ISSUE THREAD

**Issue by zeydo** [fabianfiorotto/quick-query#53]
**DBMS I'm using:**  Mysql
**OS I'm using:**   MAC
**Theme I'm using:** Dark
**Atom version:**  1.27.2
Hello there,
First of all thank you for your work.
I am using "ftp remote edit" and usually do not work by opening a project folder.
I usually access the project via ftp and I always have to write my MySQL connection information again and again.
Does this have a solution?
I apologize for the bad english. I hope you understand.
Thank you.

**Comment by fabianfiorotto** [comment]
Is your MySQL connection still visible in the connection browser after using this other package? What does happen when you try to navigate it?

**Comment by zeydo** [comment]
The other package does not have this package problem.
The Mysql connection information is lost because I only open the editor without any project.

**Comment by fabianfiorotto** [comment]
I understand. You want to store your connection credentials globally and not associated with a project. To implement this I would need to store files in the _~/.atom_ directory. I have to read a little more about this because I never did it before.

I think that it should be a configuration to toggle this functionality on/off.

**Comment by zeydo** [comment]
The [data-atom](https://github.com/lukemurray/data-atom) is what I'm talking about.
I'm getting server information from a json file.

**Comment by fabianfiorotto** [comment]
Yes. I already thought that. But importing and exporting connection credentials could be just as annoying as entering them manually.

**Comment by zeydo** [comment]
I think a necessary feature. 
I think it's a necessary feature.
If you want, you can tell me how to do it.

**Comment by fabianfiorotto** [comment]
I was researching how `ftp-remote-edit` stores its connection credentials. It encrypts the information and stores it as a config. Encrypt the information is kinda silly because the password to decrypt it is stored in the same config file. I think we could do the same here but instead of encrypting we could use a simple base64 encoding.

I also could add the options to export/import connection as a contextual menu.

**Comment by zeydo** [comment]
Yes, I would look forward to it.
Thank you
