### ISSUE TITLE
Failed to install quick-query because Git was not found.

### ISSUE THREAD

**Issue by tiagocaus** [fabianfiorotto/quick-query#62]
Installing “quick-query@1.1.1” failed.Hide output…
Failed to install quick-query because Git was not found.

The quick-query package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com

Run apm -v after installing Git to see what version has been detected.

**OS I'm using:**   ((Windows 10))
**Atom version:**  ((1.40.0))

**Comment by fabianfiorotto** [comment]
Are you able to install any other package?

**Comment by tiagocaus** [comment]
Yes, I have other packages installed.

**Comment by fabianfiorotto** [comment]
Do you have GIT installed? You need it in order to install complex packages like this one.

Also, make sure that the git executable is listed in the PATH environment variable.

**Comment by tiagocaus** [comment]
I didn't know I needed to install GIT, because in the other modules I installed, it wasn't necessary.

Could inform the link from where I can download the necessary installer, is the first time I install.

I use Windows 10.


Thank you.

**Comment by fabianfiorotto** [comment]
Others modules don't require GIT because are more simple and don't have dependencies. This package depends on other repositories that allow connecting to databases etc.

You can install the official version with the basic git commands
https://git-scm.com/download/win

That should be enough if you don't want to use git in your own project.

Or you can download git for windows witch comes with GUI tools
https://gitforwindows.org/

Also, GitHub has its own git GUI tools based on electron (like atom)
https://git-scm.com/download/win

SOURCE: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git#_installing_on_windows

**Comment by cherylthy** [comment]
Hi, how do I make sure that the git executable is listed in the PATH environment variable?

**Comment by cheryl04** [comment]
Hi, I'm having problems with the PATH environment variable. 

How do I make sure that the git executable is listed in the PATH environment variable?
